### ISSUE TITLE
sever容器会反复重启

### ISSUE THREAD

**Issue by coollce** [awake1t/linglong#81]
添加扫描网段执行扫描之后，容器会没隔十几秒就重启，基本和masscan扫描周期一致

**Comment by coollce** [comment]
[5 rows affected or returned ] 
2022/10/11 00:20:35 **initialization failed: invalid character 'd' in string escape code**
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf3faaf]

goroutine 233 [running]:
linglong/routers/api/v1/alyaze.(*WebAnalyzer).Process(0x0, 0xc00050ac68, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/lan/tools/git_tools/awake1t/linglong/routers/api/v1/alyaze/webanalyze.go:84 +0x10f
linglong/routers/api/v1.CheckFinger.func2(0xc00046ca20, 0xc00044f970)
	/Users/lan/tools/git_tools/awake1t/linglong/routers/api/v1/Iplist.go:584 +0x1af
created by linglong/routers/api/v1.CheckFinger
	/Users/lan/tools/git_tools/awake1t/linglong/routers/api/v1/Iplist.go:580 +0x40e
